name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python development tools
      run: sudo apt-get install python3-dev

    - name: Install dependencies
      run: |
        pip install buildozer
        # Add any other dependencies your project needs

    - name: Build application
      run: buildozer -v -p buildozer.spec android debug
