name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python and dependencies
      run: |
        sudo apt-get install -y python3 python3-pip python3-setuptools python3-wheel zlib1g-dev
        python3 -m pip install --upgrade pip

    - name: Install buildozer and dependencies
      run: |
        sudo apt-get install -y cython
        pip install buildozer
        # Add any other dependencies your project needs

    - name: Build application
      run: buildozer -v -p buildozer.spec android debug
